# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Visa Check' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Visa Check
  pod 'lottie-ios'
  pod "SearchTextField"
  pod 'Firebase/Core'
  pod 'Firebase/Database'
end
